apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-bcn6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-unms-tenant/rhtap-demo-app/hacbs-test-project-bcn6@sha256:7100dc6b762f308d79c8e0848587c00d025b6ee4e7bc187a16e681970c0a6030
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
