apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-bcn6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-bcn6
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-bcn6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-bcn6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-bcn6
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-unms-tenant/rhtap-demo-app/hacbs-test-project-bcn6@sha256:a8878b32195c837f2dff7711ec5ae532ea4c7bc11c465115431e8ac76af08cca
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
